### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by amilajack** [varun-d/ampsper#2]
Screenshots of the theme would be a great addition to this project.

**Comment by varun-d** [comment]
Hi @amilajack there have been a few updates:

1. Mainly that this is the exact copy of Casper theme, no design changes but you are right it should have screenshots anyway.

2. Ghost themselves have announced support for AMP in a new upcoming version so I am going to stop working on this project and start with a new theme for RTL (Arabic) support, *with screenshots*
